name: article-project

services:
  postgres: 
    image: article-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=spring
      - POSTGRES_USER=psql
      - POSTGRES_PASSWORD=123
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

volumes:
  db-data: 