services:
  postgres: 
    build: ./database
    restart: unless-stopped
    environment:
      - POSTGRES_DB=spring
      - POSTGRES_USER=psql
      - POSTGRES_PASSWORD=123
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  db-data: 