POST http://127.0.0.1:8081/oauth2/token
Content-Type: application/x-www-form-urlencoded   

grant_type=authorization_code
&code=NmXdNVOaOAF5C6myggTd1LE5aC_SZ7AJTtEDBctQprb9YlmyQdtZjyw-eJhKpqXhnW9LB3_JvtKnBm5SmrXWLxUefQB5FTIeCPj0Xt-dweDxZxRFgk4nssH_LqUMqp8j
&client_id=debug
&client_secret=secret
&redirect_uri=https://oidcdebugger.com/debug
###
GET http://127.0.0.1:8082/articles
Authorization: Bearer eyJraWQiOiJjYmI5ZWRhMC03NmRhLTQ4N2YtYTMxZS02YTQwODk4NWVhZjEiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJzcHJpbmctYWRtaW4iLCJhdWQiOiJkZWJ1ZyIsIm5iZiI6MTczMDM0Njk3Nywic2NvcGUiOlsiYXJ0aWNsZXMucmVhZCJdLCJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwODEiLCJleHAiOjE3MzAzNTA1NzcsImlhdCI6MTczMDM0Njk3NywianRpIjoiNjY2ZGM5NWEtMTY5Ni00ZDIyLTkyN2EtZmJkMWEyOGRlOWNhIn0.YpHNNdYTqkVT8UVjzc5ihGrT6rH5s3tUblN6JLL4zC98hTYJRxIk9JX882UbdoyLoGdAuKRsFFPN1B-VXN1tcN-X-CjAtGelqUbrnfXrkjoTb7tnw-aCbUXI65Fg51GUGwlDN_b6OO_kC1NzU_IdBL35xNzbgrHhbSo55qBH5_ZFRfnoq7XRad6rQW_GVSi3TKdyxF9JPgv76vUt-W7NoiwOHbJH4f1b7C5z76xo5-wF6mUbXQqxUKWmuxb-VYF4nx6e25TGJey96oaDg8dJThT0LNqZKpoYzO1gBSGjgkA9_ygIGmXfSwWCOP1AOj3-iFvzJWR96-6PAJkYlhG2qA
###
GET http://127.0.0.1:8081/users/profile
Authorization: Bearer eyJraWQiOiI3YzBlZGQ2Yy1mNTU1LTQ4NjEtODBhZC0yMjI1Nzk5NzhjMWQiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiYXVkIjoiZGVidWciLCJuYmYiOjE3MzAyNjkyODMsInNjb3BlIjpbInByb2ZpbGUiXSwiaXNzIjoiaHR0cDovLzEyNy4wLjAuMTo4MDgwIiwiZXhwIjoxNzMwMjcyODgzLCJpYXQiOjE3MzAyNjkyODMsImp0aSI6IjNkM2Q4ZTY0LTk4NDMtNDQ3My1iM2E2LTI5MDY5MTNkNWZkNyJ9.ksdG9Imluei2T_wKAVNA5AIvjEqqbJbV6qiKIm71ampoNKRdmoQLjpCQna877oQgFZLo7Bw88KXv7E5PSae_d38xF7EWN4ugeHG5r0gTVmFnZXwxX4bBLGcNOPYdTCsAWSlOJ_KU2vMA3m4kbhsLd_orxdp6Bq_cMPZeadelEfLEQfBz7k_S0UDERIYICdZ3r0iebN3LUHz0SEa7ZD0lL3qJ3HZh9lfnTWHSNG5qXQ7W_Js35zxMADiqksoSJSE4oSo_Xe172F4_9j0xY_hJIxGnRYjCUZQWEjQhR0gHWad0hnHD-cotWBA3lQLXwmzUO_2tWNBhimW8Ans9lfDDtQ
