POST http://127.0.0.1:8080/oauth2/token
Content-Type: application/x-www-form-urlencoded   

grant_type=authorization_code
&code=xua9hVjErDduV4mEc3zBKG6Bh-qKxI5GT50eXMlHqMBMYIYlCZ_gxjciQdic4Wqh9KI06CXrQ4270dU5qVYjXocR_SpZAfgnMdtQNcU9EKBNnGfTQ6rfjJ_7cHr4EZPd
&client_id=debug
&client_secret=secret
&redirect_uri=https://oidcdebugger.com/debug
###
GET http://127.0.0.1:8081/articles
Authorization: Bearer eyJraWQiOiI0ODM1ZTg1Zi00YzBkLTRiZTgtOWNiYy1lOWNhNDcwNGI2OGYiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJzcHJpbmctYWRtaW4iLCJhdWQiOiJkZWJ1ZyIsIm5iZiI6MTczMDE5NDUzNiwic2NvcGUiOlsiYXJ0aWNsZXMucmVhZCJdLCJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwODAiLCJleHAiOjE3MzAxOTgxMzYsImlhdCI6MTczMDE5NDUzNiwianRpIjoiNTg4ZTdlZjktN2M3ZS00Yzc2LThmMzItNGRlZWZkMTUxZDJjIn0.X_WIrJr1X2NYQlg1ep15WpVzpdg78kjNUnsMPbaosPvY3XPmCwgPkonakMC7KYQxUUUzjfh45W2iSFvkvXP8h8qZhlsrDA9hYdZFbkTzft9vlcn4CYJmg4KIa6mki1URNUVL6S_ErLTv4l5TAw1x3GwlwFJ-r8xdp16jw-TSn_d7CVN5opUbk8cIrP8_3FdWvwdgdUR8GlHc6yIjBppfJdgMEuOKBQoaRxi4BIJYEr6z5D91E8FFpN5bbDGEp5oefW8CyTMdgbL7O8W4mKXv3gzgDw9qQ_bvybzDJ2iPvlaIsBulS2q23DPptavvqPtzd3vDE4Rrjz4TdD1WGM2xyg
###
GET http://127.0.0.1:8080/users
Authorization: Bearer eyJraWQiOiI0ODM1ZTg1Zi00YzBkLTRiZTgtOWNiYy1lOWNhNDcwNGI2OGYiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJzcHJpbmctYWRtaW4iLCJhdWQiOiJkZWJ1ZyIsIm5iZiI6MTczMDE5NDUzNiwic2NvcGUiOlsiYXJ0aWNsZXMucmVhZCJdLCJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwODAiLCJleHAiOjE3MzAxOTgxMzYsImlhdCI6MTczMDE5NDUzNiwianRpIjoiNTg4ZTdlZjktN2M3ZS00Yzc2LThmMzItNGRlZWZkMTUxZDJjIn0.X_WIrJr1X2NYQlg1ep15WpVzpdg78kjNUnsMPbaosPvY3XPmCwgPkonakMC7KYQxUUUzjfh45W2iSFvkvXP8h8qZhlsrDA9hYdZFbkTzft9vlcn4CYJmg4KIa6mki1URNUVL6S_ErLTv4l5TAw1x3GwlwFJ-r8xdp16jw-TSn_d7CVN5opUbk8cIrP8_3FdWvwdgdUR8GlHc6yIjBppfJdgMEuOKBQoaRxi4BIJYEr6z5D91E8FFpN5bbDGEp5oefW8CyTMdgbL7O8W4mKXv3gzgDw9qQ_bvybzDJ2iPvlaIsBulS2q23DPptavvqPtzd3vDE4Rrjz4TdD1WGM2xyg