POST http://127.0.0.1:8080/oauth2/token
Content-Type: application/x-www-form-urlencoded   

grant_type=authorization_code
&code=zvM8tWTgadrpTnnGzo6sorM-N8REjHGPkIKpFGM3CJ7_NYXxB7wn2WIAgVTOFtWQq3gQ4ymz4_O1bW_sRiHHsJVr1HsVwyebCfAetFnnhEs6JEhgJLuyq_e4dDxPvyWp
&client_id=debug
&client_secret=secret
&redirect_uri=https://oidcdebugger.com/debug
###
GET http://127.0.0.1:8081/articles
Authorization: Bearer eyJraWQiOiI0MmFkNzk1Ni1iYTE2LTRkMDAtOTkwZC00YmQ1YTM2ODA2ZWEiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJzcHJpbmctYWRtaW4iLCJhdWQiOiJkZWJ1ZyIsIm5iZiI6MTczMDE5NTA0Niwic2NvcGUiOlsiYXJ0aWNsZXMucmVhZCJdLCJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwODAiLCJleHAiOjE3MzAxOTg2NDYsImlhdCI6MTczMDE5NTA0NiwianRpIjoiZjhmZmQ2YjQtZWI4OS00NzY4LTg5NTEtN2E0Mjk5ZjY5NDZjIn0.s-w-vEX333TsJpMDIUVo6vCSuUy7EUP3KmJhq03nR2B51awHAhrczOlKbkQojvXgfEEIhIEh-cASexT0Hemh1U-aoWfgIfm_5O6QMzxfSS5UvLPxU-LdHDARYHuX-NhKewpgeCsqvXMd5a3WphthQ7H18pdn0TYv9Pfgp8wilxI8sgLMHcdzHp7HJyM99KQBqtM4b4LFhDT0QkimnUWrnbllxEZa3JthswwPVPHy8IqJG3uuB4C8FP5rmvM09k2EUSGVhTwM-6tfCKQaMAz-43Ex8hzHQxR_kTPIR-Cs0atwOampq_DrVxtFLJXJ7gd6wsCvJF6FH2fDgp1xHJdMkg
###
GET http://127.0.0.1:8080/users/profile
Authorization: Bearer eyJraWQiOiI3YzBlZGQ2Yy1mNTU1LTQ4NjEtODBhZC0yMjI1Nzk5NzhjMWQiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiYXVkIjoiZGVidWciLCJuYmYiOjE3MzAyNjkyODMsInNjb3BlIjpbInByb2ZpbGUiXSwiaXNzIjoiaHR0cDovLzEyNy4wLjAuMTo4MDgwIiwiZXhwIjoxNzMwMjcyODgzLCJpYXQiOjE3MzAyNjkyODMsImp0aSI6IjNkM2Q4ZTY0LTk4NDMtNDQ3My1iM2E2LTI5MDY5MTNkNWZkNyJ9.ksdG9Imluei2T_wKAVNA5AIvjEqqbJbV6qiKIm71ampoNKRdmoQLjpCQna877oQgFZLo7Bw88KXv7E5PSae_d38xF7EWN4ugeHG5r0gTVmFnZXwxX4bBLGcNOPYdTCsAWSlOJ_KU2vMA3m4kbhsLd_orxdp6Bq_cMPZeadelEfLEQfBz7k_S0UDERIYICdZ3r0iebN3LUHz0SEa7ZD0lL3qJ3HZh9lfnTWHSNG5qXQ7W_Js35zxMADiqksoSJSE4oSo_Xe172F4_9j0xY_hJIxGnRYjCUZQWEjQhR0gHWad0hnHD-cotWBA3lQLXwmzUO_2tWNBhimW8Ans9lfDDtQ
