server:
  port: 8080

spring:
  application:
    name: auth-server

  security:
    oauth2:
      authorizationserver:
          issuer: http://127.0.0.1:8080
          client:
            articles-client:
              registration:
                client-id: articles-client
                client-secret: "{noop}123123123"
                client-name: Articles Client
                client-authentication-methods:
                  - client_secret_post
                authorization-grant-types:
                  - authorization_code
                  - refresh_token
                redirect-uris:
                  - http://127.0.0.1:8082/login/oauth2/code/spring
                scopes:
                  - openid
                  - articles.read
            debug:
              registration:
                client-id: debug
                client-secret: "{noop}secret"
                client-name: Articles Client
                client-authentication-methods:
                  - client_secret_post
                authorization-grant-types:
                  - authorization_code
                  - refresh_token
                redirect-uris:
                  - https://oidcdebugger.com/debug
                scopes:
                  - openid
                  - articles.read
