spring:
  application:
    name: article-server

  profiles:
    active: default
  
  config:
    import: "optional:configserver:"

  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: config-server
  
eureka:
  client:
      fetch-registry: true
      register-with-eureka: true
      serviceUrl:
        defaultZone: http://127.0.0.1:8761/eureka

