apiVersion: apps/v1
kind: Deployment
metadata:
  name: article-article-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: article-client
  template:
    metadata:
      labels: 
        app: article-client
    spec:
      containers:
        - name: article-client
          image: khoildm2508/article-client
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports: 
          - containerPort: 80
          - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: article-client
spec:
  type: LoadBalancer
  selector:
    app: article-client
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
