apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: article-db-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: article-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: article-db
  template:
    metadata:
      labels: 
        app: article-db
    spec:
      containers:
        - name: article-db
          image: khoildm2508/article-db
          env:
            - name: POSTGRES_DB
              value: spring
            - name: POSTGRES_PASSWORD
              value: "123"
            - name: POSTGRES_USER
              value: psql
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports: 
          - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: article-db-data
      volumes:
        - name: article-db-data
          persistentVolumeClaim:
            claimName: article-db-data
---
apiVersion: v1
kind: Service
metadata:
  name: article-db
spec:
  type: LoadBalancer
  selector:
    app: article-db
  ports: 
    - protocol: TCP
      port: 5432
      targetPort: 5432