apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels: 
        app: eureka
    spec:
      containers:
        - name: eureka
          args:
            - '--spring.profiles.active=docker'
          image: khoildm2508/eureka
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports: 
          - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: eureka
spec:
  # type: LoadBalancer
  type: NodePort
  selector:
    app: eureka
  ports:
    - name: http
      protocol: TCP
      port: 8761
      targetPort: 8761
