name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup NodeJS 23.x
      uses: actions/setup-node@v4 
      with:
        node-version: 23.x
        cache-dependency-path: article-client
        cache: 'npm'
    
    - name: Build and publish
      run: bash build.sh
